# Generated by Django 4.1.7 on 2023-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLthietbi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
