# Generated by Django 4.1.7 on 2023-05-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLthietbi_app', '0002_alter_thietbi_mo_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='ngay_bao_tri',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bảo trì'),
        ),
    ]
